const REQUIRED_ENV_STRINGS = [
  'NODE_ENV',
  'API_TOKEN',
  'JWT_SECRET'
];
const REQUIRED_ENV_NUMBERS = [
  'NODE_PORT'
];
const REQUIRED_ENV_BOOLEANS = [

];

module.exports = {
  REQUIRED_ENV_STRINGS,
  REQUIRED_ENV_NUMBERS,
  REQUIRED_ENV_BOOLEANS,
};